name: Create and Attach Soundpack Zips

on:
  release:
    types: [published]

jobs:
  zip_and_attach:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up zip utility
      run: sudo apt-get install zip

    - name: Create zip files for each soundpack
      run: |
        mkdir -p zips
        for dir in soundpacks/*; do
          if [ -d "$dir" ]; then
            zip -r "zips/$(basename "$dir").zip" "$dir"
          fi
        done

    - name: List generated zip files
      run: ls -l zips

    - name: Get release upload URL
      id: get_release_upload_url
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: releases } = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          const release = releases.find(r => r.tag_name === context.payload.release.tag_name);
          if (!release) {
            throw new Error(`Release not found for tag ${context.payload.release.tag_name}`);
          }
          core.setOutput('upload_url', release.upload_url);

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release_upload_url.outputs.upload_url }}
        asset_path: zips/*.zip
        asset_name: soundpack-zips
        asset_content_type: application/zip
