name: Create and Attach Soundpack Zips

on:
  release:
    types: [published]

jobs:
  zip_and_attach:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up zip utility
      run: sudo apt-get install zip

    - name: Create zip files for each soundpack
      run: |
        for dir in soundpacks/*; do
          if [ -d "$dir" ]; then
            zip -j "${dir##*/}.zip" "$dir"/*.ogg
          fi
        done

    - name: List generated zip files
      run: ls -l *.zip


    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: "*.zip"
        tag: ${{ github.event.release.tag_name }}
        overwrite: true
        file_glob: true
